In [1]:
import numpy as np
weights = np.array([0.1, 0.2, 0])
def neural_network(input, weights):
    pred = input.dot(weights)
    return pred
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)


0.9800000000000001


In [4]:
weights = [0.3, 0.2, 0.9]
def ele_mul(number, vector):
    output = [0,0,0]
    assert(len(output)== len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output
def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input, weights)

print(pred)

[0.195, 0.13, 0.5850000000000001]


In [8]:
def w_sum(a,b):
    assert(len(a)==len(b))
    output=0
    for i in range(len(a)):
        output += (a[i]*b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect)== len(matrix))
    output=[0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output
def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

# outter array is group for prediction, inner array is each input weight
weights = [[0.1, 0.1, -0.3], [0.1, 0.2, 0.0], [0.0, 1.3, 0.1]] 

# input
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


In [10]:
ih_wgt = [[0.1, 0.2, -0.1], [-0.1, 0.1, 0.9], [0.1, 0.4, 0.1]]
hp_wgt = [[0.3, 1.1, -0.3], [0.1, 0.2, 0.0], [0.0, 1.3, 0.1]]
weights= [ih_wgt, hp_wgt]
# input
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(input, weights[1])
    return pred

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

[2.905, 0.9800000000000001, 0.9650000000000001]


In [16]:
import numpy as np
ih_wgt = np.array([[0.1, 0.2, -0.1], [-0.1, 0.1, 0.9], [0.1, 0.4, 0.1]]).T
hp_wgt = np.array([[0.3, 1.1, -0.3], [0.1, 0.2, 0.0], [0.0, 1.3, 0.1]]).T
weights = [ih_wgt, hp_wgt]

print(weights)

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = input.dot(weights[1])
    return pred

# input
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

[array([[ 0.1, -0.1,  0.1],
       [ 0.2,  0.1,  0.4],
       [-0.1,  0.9,  0.1]]), array([[ 0.3,  0.1,  0. ],
       [ 1.1,  0.2,  1.3],
       [-0.3,  0. ,  0.1]])]
[2.905 0.98  0.965]


In [14]:
a = np.array([[0.1, 0.2, -0.1], [-0.1, 0.1, 0.9], [0.1, 0.4, 0.1]])
print(a)
b = np.array([[0.1, 0.2, -0.1], [-0.1, 0.1, 0.9], [0.1, 0.4, 0.1]]).T
print(b)

[[ 0.1  0.2 -0.1]
 [-0.1  0.1  0.9]
 [ 0.1  0.4  0.1]]
[[ 0.1 -0.1  0.1]
 [ 0.2  0.1  0.4]
 [-0.1  0.9  0.1]]
